name: Clang Format Check

on:
  push:
    branches: [ '*' ]

  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check clang-format version
      run: clang-format --version

    - name: Run clang-format check
      run: |
        find . \( -name '*.h' -o -name '*.cpp' -o -name '*.hpp' -o -name '*.cxx' -o -name '*.cc' \) -print0 | 
        xargs -0 clang-format -style=file -i
        git diff --exit-code

    - name: Check for changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Clang-format check failed. The following files are not properly formatted:"
          git status --porcelain
          exit 1
        else
          echo "Clang-format check passed. All files are properly formatted."
        fi
